organizations_index:
    path:     /
    defaults: { _controller: "HandissimoBundle:Organizations:index" }
    methods:  GET

organizations_show:
    path:     /{id}/show
    defaults: { _controller: "HandissimoBundle:Organizations:show" }
    methods:  GET

organizations_new:
    path:     /new
    defaults: { _controller: "HandissimoBundle:Organizations:new" }
    methods:  [GET, POST]

organizations_edit:
    path:     /{id}/edit
    defaults: { _controller: "HandissimoBundle:Organizations:edit" }
    methods:  [GET, POST]

organizations_delete:
    path:     /{id}/delete
    defaults: { _controller: "HandissimoBundle:Organizations:delete" }
    methods:  DELETE


