HandissimoBundle\Entity\StaffTypes:
    type: entity
    table: staff_types
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        secteur:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    oneToMany:
        typesstaff:
            targetEntity: Staff
            mappedBy: staff

    lifecycleCallbacks: {  }